name: Automated Data Preprocessing Pipeline

on:
  push:
    branches: [ main ]
    paths:
      - 'titanic_raw.csv'
      - 'automate_Raffy_Akhsan_Adi_Muzacky_APC225D6Y0365.py'
      - '.github/workflows/preprocessing.yml'
  workflow_dispatch:

jobs:
  preprocessing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy scikit-learn

      - name: Run Preprocessing Pipeline
        run: python automate_Raffy_Akhsan_Adi_Muzacky_APC225D6Y0365.py

      - name: Upload Preprocessed Dataset as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: titanic-preprocessed
          path: titanic_preprocessing.csv
